systemd_dir: /etc/systemd/system
k3s_version: v1.23.6+k3s1
router_ip: 192.168.2.1
name_servers:
  - 192.168.2.1
  - 8.8.8.8
  - fe80::1
system_log_dir: /var/log
system_bin_dir: /usr/bin
local_bin_dir: /usr/local/bin
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
