---
- name: Restore dhcpcd.conf backup
  import_role:
    name: reset
    tasks_from: restore
  vars:
    file: /etc/dhcpcd.conf

- name: Remove sshd fix
  lineinfile:
    path: /etc/ssh/sshd_config
    line: IPQoS 0x00
    state: absent

- name: Stop blanking service
  systemd:
    name: enable-console-blanking.service
    state: stopped
    enabled: no

- name: Remove blanking service
  file:
    path: /etc/systemd/system/enable-console-blanking.service
    state: absent

- name: Remove fdk user
  user:
    name: fdk
    state: absent

- name: Remove fdk home directory
  file:
    path: /home/fdk
    state: absent
