---
- hosts: pi.fdk.codes
  gather_facts: no
  become: yes
  roles:
    - rpi/reset
    - k3s/reset
    - terraform/reset
    - aws/reset
    - helm/reset
    - role: fdk/reset
      become: yes
      become_user: fdk