---
- hosts: k3s_cluster
  become: yes
  roles:
    - role: k3s

- hosts: master
  become: yes
  roles:
    - role: ethernet
    - role: k3s/master
    - role: terraform
    - role: aws
    - role: helm
    - role: fdk

- hosts: node
  become: yes
  roles:
    - role: wifi
    - role: touchscreen
    - role: sshfix
    - role: k3s/node
