---
- hosts: k3s_cluster
  become: true
  roles:
    - rpi
    - k3s
    - fdk

- hosts: master
  become: true
  roles:
    - ethernet
    - k3s/master
    - terraform
    - aws
    - helm

- hosts: node
  become: true
  roles:
    - ethernet
    - k3s/node
    - touchscreen
    - sshfix
