---
- name: Setup Raspberry Pi
  hosts: pi.fdk.codes
  become: yes
  roles:
    - rpi
    - k3s
    - k3s/master
    - terraform
    - aws
    - helm
    - role: fdk
      become: yes
      become_user: fdk
