---

- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k3s
    - k3s-node

- name: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  register: pkill_containerd_shim_runc
  command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: Umount k3s filesystems
  include_role:
    name: reset
    tasks_from: umount
  vars:
    items:
      - /run/k3s
      - /var/lib/kubelet
      - /run/netns
      - /var/lib/rancher/k3s
  loop: "{{ items }}"
  loop_control:
    loop_var: mounted_fs

- name: Remove service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - "{{ systemd_dir }}/k3s.service"
    - "{{ systemd_dir }}/k3s-node.service"
    - /etc/rancher/k3s
    - /var/lib/kubelet
    - /var/lib/rancher/k3s

- name: daemon_reload
  systemd:
    daemon_reload: yes

- name: Remove kubectl symlink
  file:
    path: /usr/local/bin/kubectl
    state: absent

- name: Remove crictl symlink
  file:
    path: /usr/local/bin/crictl
    state: absent

# - name: Restore /boot/cmdline.txt backup
#   import_role:
#     name: reset
#     tasks_from: restore
#   vars:
#     file: /boot/cmdline.txt