---
- name: Find terraform archives
  find:
    paths: /tmp
    recurse: no
    patterns: "terraform-*.zip"
  register: tf_archives

- name: Remove terraform archives
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ tf_archives.files }}"

- name: Uninstall terraform
  file:
    path: /usr/local/bin/terraform
    state: absent
