---

- name: Check k3s version
  ansible.builtin.shell: set -o pipefail && k3s --version 2>&1 | head -n 1 | grep -q {{ k3s_version }}
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  register: k3s_versions_match

- import_tasks: prereq.yml
- import_tasks: download.yml
  when: k3s_versions_match.rc != 0
- import_tasks: config.yml
