---
- name: Set detected_distribution to Raspbian
  set_fact:
    detected_distribution: Raspbian
  when: >
    ansible_facts.lsb.id|default("") == "Raspbian" or
    ansible_facts.lsb.description|default("") is match("[Rr]aspbian.*")

- name: Execute raspbian related prereq tasks
  include_tasks: prereq/raspbian.yml
  when:
    - detected_distribution | default("") == "Raspbian"

- name: Execute ubuntu related prereq tasks
  include_tasks: prereq/ubuntu.yml
  when:
    - ansible_distribution | default("") == "Ubuntu"