---

- name: Download terraform linux archive x64
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    checksum: sha256:https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS
    dest: /tmp/terraform-{{ terraform_version }}.zip
  when: ansible_facts.architecture == "x86_64"

- name: Download terraform linux archive arm64
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_arm64.zip
    checksum: sha256:https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS
    dest: /tmp/terraform-{{ terraform_version }}.zip
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Download terraform linux archive armhf
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_arm.zip
    checksum: sha256:https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS
    dest: /tmp/terraform-{{ terraform_version }}.zip
  when:
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"