---

- name: Check terraform version
  command: "terraform version 2>&1 | head -n 1 | grep -q {{ terraform_version }}"
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- include_tasks: download.yml
  when: terraform_versions_match.rc != 0

- name: Install unzip to unarchive terraform
  package:
    name: unzip
    state: present

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{ terraform_version }}.zip
    dest: "/usr/local/bin"
    copy: no
  when: terraform_versions_match.rc != 0
