---

- name: Check terraform version
  shell: set -o pipefail && terraform version 2>&1 | head -n 1 | grep -q {{ terraform_version }}
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- include_tasks: download.yml
  when: terraform_versions_match.rc != 0

- name: Install unzip to unarchive terraform
  package:
    name: unzip
    state: present

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{ terraform_version }}.zip
    dest: "/usr/local/bin"
    copy: no
  when: terraform_versions_match.rc != 0

- name: Check if autocomplete is installed
  lineinfile:
    path: ~/.bashrc
    line: complete -C /usr/local/bin/terraform terraform
    state: absent
  check_mode: yes
  register: tf_autocomplete
  changed_when: tf_autocomplete.found == 0

- name: Install terraform autocomplete
  command: terraform -install-autocomplete
  when: tf_autocomplete.found == 0
