---
- name: Install tmux
  package:
    name: tmux
    state: present

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    update: no
    version: master

- name: Add tmux config
  template:
    src: "tmux.conf.j2"
    dest: "~/.tmux.conf"
    owner: root
    group: root
    mode: 0644