---
- name: Find helm archives
  find:
    paths: /tmp
    recurse: no
    patterns: "helm-*.tar.gz"
  register: tf_archives

- name: Remove helm archives
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ tf_archives.files }}"

- name: Uninstall helm
  file:
    path: /usr/local/bin/helm
    state: absent
