---
- name: Find helm archives
  find:
    paths: /tmp
    recurse: no
    patterns: "helm-*.tar.gz"
  register: helm_archives

- name: Remove helm archives
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ helm_archives.files }}"

- name: Uninstall helm
  file:
    path: /usr/local/bin/helm
    state: absent

- name: Remove helm autocomplete
  lineinfile:
    path: ~/.bashrc
    line: source <(helm completion bash)
    state: absent

- name: Remove KUBECONFIG export
  lineinfile:
    path: ~/.profile
    line: "export KUBECONFIG={{ kube_config_path }}"
    state: absent
