---
- name: collect facts about system services
  ansible.builtin.service_facts:

- import_tasks: setup.yml
  when:
    (ansible_facts['services']['k3s.service'] is not defined) or
    (ansible_facts['services']['k3s.service']['state'] == 'stopped') or
    (k3s_versions_match.rc != 0)
